theme: chulapa-jekyll
# Site settings
title: TeamSerio.us
email: we-do-not-have-email@example.com
description: >-
  Web Home Of Team Serious.
baseurl: ""
url: "https://teamserio.us"
github_username: rykerwilliams
timezone: America/New_York
og_image: assets/images/site/SeriousManaHR-blacklogo-gray.png

author:
  name: Rajah James
  avatar: assets/images/avatars/310221.jpg
  location: Ohio, US
  links:
    - url: https://bsky.app/profile/cleverpseudonym.bsky.social
      label: "My personal bsky"
    - url: https://x.com/rykerwilliams
      icon: "fab fa-twitter"
      label: "My personal X"
    - url: https://www.facebook.com/rajah.james
      icon: "fab fa-facebook"
      label: "My personal FB"

search:
  provider : lunr
  label :
  landing_page :
  lunr_maxwords :

comments:
  provider:
  disqus_shortname:

navbar:
  style : dual
  brand:
    title:
    img: "./assets/images/site/ohio.png"
  nav:
    - title : Posts
      url : /posts/
    - title : Calendar
      url : /calendar
    - title : Tags
      url : /tags
    - title : Categories
      url : /categories
    - title : Merch
      url : /merch/
    - title : Media
      child:
        - title : Full Warning Podcast
          url: /full-warning/
        - title : Full Warning YouTube
          url: https://www.youtube.com/@FullWarningPodcast
        - title : Serious Vintage Podcast
          url: https://www.eternalcentral.com/seriousvintagepodcast/
        - title : Serious Vintage YouTube
          url: https://www.youtube.com/@SeriousVintageCast

footer:
  copyright: "&copy; 2024 Team Serious"
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url: "./atom.xml"

googlefonts:

chulapa-skin:
  skin : twitter-dim
  highlight : "ZENBURN"
  autothemer : false
  vars :
    primary : lightskyblue

paginate: 4
paginate_path: "/posts/page:num/"
paginator_maxnum: 3

collections:
  posts:
    output: true
    permalink : /posts/:year:month:day_:title
  merch:
    output: true
    permalink: /merch/:name

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search : false
      cloudtag_url : /tags
      cloudcategory_url : /categories
  - scope:
      path: ""
      type: "posts"
    values:
      header_type : "post"
      include_on_search : true
      include_on_feed : true
      show_date : true
      show_related : true
      show_bottomnavs : true
      show_sociallinks : true
      show_comments : true
      show_tags : true
      show_categories : true
      show_author : true
      show_breadcrumb : true
      breadcrumb_list :
        - label: Posts
          url: /posts
  - scope:
      path: ""
      type: "merch"
    values:
      layout: "merch-item"
      include_on_search: false

plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

include:
  - _pages

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
