theme: chulapa-jekyll


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TeamSerio.us
email: we-do-not-have-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Web Home Of Team Serious.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.teamserio.us" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  rykerwilliams
timezone: America/New_York
og_image: assets/images/index/SeriousManaHR-blacklogo.png
author:
  name: Rajah James
  avatar: https://avatars.githubusercontent.com/u/310221
  location: Ohio, US
  links:
    - url: https://bsky.app/profile/cleverpseudonym.bsky.social
      label: "My personal bsky"
    - url: https://x.com/rykerwilliams
      icon: "fab fa-twitter"
      label: "My personal X"
    - url: https://www.facebook.com/rajah.james
      icon: "fab fa-facebook"
      label: "My personal FB"

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/
search:
  provider              : lunr #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled
  landing_page          :  #default ["/search"] Link on navbar
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build

comments:
  provider:         #Use 'disqus' https://disqus.com/ or 'giscus' https://giscus.app/
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/

# Navbar:
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style : dual 
  brand:
    title:
    img: "./assets/images/site/ohio.png"
  nav:
  - title: Blog #Label
    url: /blog/  #url
  - title: Podcast #Label
    child: 
      - title : Full Warning
        url: /full-warning/  #url
      - title : Serious Vintage
        url: https://www.eternalcentral.com/seriousvintagepodcast/  #url
  - title   : Extras
    child   :
      - title : Tags
        url   : /tags
      - title : Categories
        url   : /categories
  - title: Two-level link #Label
    child:
    - title: Second level first item
      url: /url2-1
    - title: Second level second item
      url: /url2-2
  - title: One-level link #Label
    url: /url1/  #url
footer:
  copyright: "&copy; 2024 Team Serious"
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    # - label: "Twitter"
    #   icon: "fab fa-twitter"
    #   url: https://twitter.com/
    # - label: "Facebook"
    #   icon: "fab fa-facebook"
    #   url: https://www.facebook.com

# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

# Theme and colors
chulapa-skin:
  skin   : twitter-dim
  highlight   : "ZENBURN" #or any other name, default is 'DEFAULT' style
  autothemer    :  false # Bool: Use autotheming
  vars          :
    primary     : lightskyblue #default ["#007bff"] - Bootstrap blue

# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  posts:
    output: true
    permalink : /blog/:year:month:day:title
collections_dir     :
permalink           : /:year:month:day:title/

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags #This is where the link on tags would redirect
      cloudcategory_url   : /categories #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Blog
          url: /blog

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
 - _pages
#  - _plugins

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

 # Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
